/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leon King
 */
import java.awt.image.ImageFilter;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

public class Lab6Gui extends javax.swing.JFrame {

    /**
     * Creates new form Lab6Gui
     */
    public Lab6Gui() {

        initComponents();
        setSize(850,660);
        setTitle("Lab6Gui");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        loadDefinitionButton = new javax.swing.JButton();
        broadcastButton = new javax.swing.JButton();
        loadImageButton = new javax.swing.JButton();
        saveDefinitionButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        loadImage1 = new javax.swing.JButton();
        sendServerButton = new javax.swing.JButton();
        pictureField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        handleField = new javax.swing.JTextField();
        nameField1 = new javax.swing.JTextField();
        removeSelector = new javax.swing.JRadioButton();
        userSelected = new javax.swing.JRadioButton();
        statusBar = new javax.swing.JLabel();
        currentGroupField = new javax.swing.JLabel();
        groupSelected1 = new javax.swing.JRadioButton();
        addSelector = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        loadDefinitionButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loadDefinitionButton.setText("Load Definition");
        getContentPane().add(loadDefinitionButton);
        loadDefinitionButton.setBounds(480, 340, 200, 60);

        broadcastButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        broadcastButton.setText("Broadcast");
        getContentPane().add(broadcastButton);
        broadcastButton.setBounds(250, 420, 210, 60);

        loadImageButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loadImageButton.setText("Load Image");
        loadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadImageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loadImageButton);
        loadImageButton.setBounds(40, 340, 190, 60);

        saveDefinitionButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saveDefinitionButton.setText("Save Definition");
        getContentPane().add(saveDefinitionButton);
        saveDefinitionButton.setBounds(250, 340, 200, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Save Definition");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 340, 200, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("Save Definition");
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 340, 200, 60);

        loadImage1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loadImage1.setText("Load Image");
        getContentPane().add(loadImage1);
        loadImage1.setBounds(40, 340, 180, 60);

        sendServerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sendServerButton.setText("Send to Server");
        getContentPane().add(sendServerButton);
        sendServerButton.setBounds(40, 420, 191, 60);

        pictureField.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Appears Here"));
        getContentPane().add(pictureField);
        pictureField.setBounds(40, 40, 220, 250);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Handle:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 110, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 50, 100, 40);

        handleField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(handleField);
        handleField.setBounds(420, 110, 320, 40);

        nameField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameField1.setText(" ");
        getContentPane().add(nameField1);
        nameField1.setBounds(420, 55, 320, 40);

        buttonGroup2.add(removeSelector);
        removeSelector.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        removeSelector.setText("Remove");
        removeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSelectorActionPerformed(evt);
            }
        });
        getContentPane().add(removeSelector);
        removeSelector.setBounds(100, 520, 150, 30);

        buttonGroup1.add(userSelected);
        userSelected.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userSelected.setSelected(true);
        userSelected.setText("User");
        getContentPane().add(userSelected);
        userSelected.setBounds(290, 210, 75, 37);

        statusBar.setText("This is the status bar");
        getContentPane().add(statusBar);
        statusBar.setBounds(0, 600, 770, 14);

        currentGroupField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currentGroupField.setText(" ");
        currentGroupField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Group", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        getContentPane().add(currentGroupField);
        currentGroupField.setBounds(240, 500, 420, 60);

        buttonGroup1.add(groupSelected1);
        groupSelected1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        groupSelected1.setText("Group");
        getContentPane().add(groupSelected1);
        groupSelected1.setBounds(430, 210, 93, 30);

        buttonGroup2.add(addSelector);
        addSelector.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addSelector.setSelected(true);
        addSelector.setText("Add");
        getContentPane().add(addSelector);
        addSelector.setBounds(30, 520, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeSelectorActionPerformed

    private void loadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadImageButtonActionPerformed
        // TODO add your handling code here:
    JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
    jfc.setDialogTitle("Select an image");
    jfc.setAcceptAllFileFilterUsed(false);
    FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG and GIF images", "png", "gif");
    jfc.addChoosableFileFilter(filter);
    
    
    int returnValue = jfc.showOpenDialog(null);
	
		if (returnValue == JFileChooser.APPROVE_OPTION) {
			File selectedFile = jfc.getSelectedFile();
			System.out.println(selectedFile.getAbsolutePath());
                        System.out.println("Opening: " + selectedFile.getName() + ".\n" );
                        
                        
		}
    
    
    
    
    
    
    
    }//GEN-LAST:event_loadImageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addSelector;
    private javax.swing.JButton broadcastButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel currentGroupField;
    private javax.swing.JRadioButton groupSelected1;
    private javax.swing.JTextField handleField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loadDefinitionButton;
    private javax.swing.JButton loadImage1;
    private javax.swing.JButton loadImageButton;
    private javax.swing.JTextField nameField1;
    private javax.swing.JLabel pictureField;
    private javax.swing.JRadioButton removeSelector;
    private javax.swing.JButton saveDefinitionButton;
    private javax.swing.JButton sendServerButton;
    private javax.swing.JLabel statusBar;
    private javax.swing.JRadioButton userSelected;
    // End of variables declaration//GEN-END:variables
}
